services:
  ethereum_parser:
    container_name: ethereum_parser
    build: .
    image: ethereum_parser:v1
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - intranalnet

  networks:
    intranalnet:
      driver: bridge
